
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE ELSE EQUALS ID IF INT LBRACE LPAREN MINUS NUMBER PLUS RBRACE RPAREN SEMI TIMES WHILEprogram : statementsstatements : statement statements\n                  | statementstatement : INT ID SEMIstatement : ID EQUALS expression SEMIexpression : expression PLUS expression\n                  | expression MINUS expression\n                  | expression TIMES expression\n                  | expression DIVIDE expressionexpression : NUMBER\n                  | ID'
    
_lr_action_items = {'INT':([0,3,9,13,],[4,4,-4,-5,]),'ID':([0,3,4,8,9,13,14,15,16,17,],[5,5,7,10,-4,-5,10,10,10,10,]),'$end':([1,2,3,6,9,13,],[0,-1,-3,-2,-4,-5,]),'EQUALS':([5,],[8,]),'SEMI':([7,10,11,12,18,19,20,21,],[9,-11,13,-10,-6,-7,-8,-9,]),'NUMBER':([8,14,15,16,17,],[12,12,12,12,12,]),'PLUS':([10,11,12,18,19,20,21,],[-11,14,-10,14,14,14,14,]),'MINUS':([10,11,12,18,19,20,21,],[-11,15,-10,15,15,15,15,]),'TIMES':([10,11,12,18,19,20,21,],[-11,16,-10,16,16,16,16,]),'DIVIDE':([10,11,12,18,19,20,21,],[-11,17,-10,17,17,17,17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statements':([0,3,],[2,6,]),'statement':([0,3,],[3,3,]),'expression':([8,14,15,16,17,],[11,18,19,20,21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statements','program',1,'p_program','parser_module.py',20),
  ('statements -> statement statements','statements',2,'p_statements','parser_module.py',24),
  ('statements -> statement','statements',1,'p_statements','parser_module.py',25),
  ('statement -> INT ID SEMI','statement',3,'p_declaration','parser_module.py',30),
  ('statement -> ID EQUALS expression SEMI','statement',4,'p_assignment','parser_module.py',40),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','parser_module.py',49),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','parser_module.py',50),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','parser_module.py',51),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','parser_module.py',52),
  ('expression -> NUMBER','expression',1,'p_expression_factor','parser_module.py',63),
  ('expression -> ID','expression',1,'p_expression_factor','parser_module.py',64),
]
